# Generated by Django 5.2.3 on 2025-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
